README.md, lib/mix/tasks/papertrail/install.ex
Let me know if you want to use `:naive_datetime` or something as default.
=> Support Ecto 2.1, by using utc_datetime as default

mix.exs, test/support/repo.ex, test/test_helper.exs
The warnings were from referencing a module that doesn't exist at compile-time.  Changing it so the referenced module is compiled fixes the errors.
=> fix test warnings

lib/paper_trail/version_queries.ex
Rearranged functions to avoid this warning:
```
warning: clauses for the same def should be grouped together, def get_version/2 was previously defined (lib/paper_trail/version_queries.ex:61)
lib/paper_trail/version_queries.ex:90
```
=> warning: clauses for the same def should be grouped together

lib/paper_trail.ex, lib/paper_trail/version_queries.ex, priv/uuid_repo/migrations/20170525133833_create_uuid_products.exs, test/paper_trail/uuid_test.exs, test/support/uuid_models.exs
=> fixed for non-regular primary key

lib/paper_trail.ex, priv/uuid_repo/migrations/20170525133833_create_uuid_products.exs, priv/uuid_repo/migrations/20170525142612_create_versions.exs, priv/uuid_repo/migrations/20170525142613_create_items.exs, test/paper_trail/uuid_test.exs, test/support/uuid_models.exs, test/test_helper.exs
Two changes:
- Better way to get model id.
- Ecto cannot cast ```integer``` to ```string``` automatically, throw exception while ```item_id``` 
type is ```:string```, ```Ecto.UUID``` <=> ```:string``` is well done.
=> get model id simply, and type check

lib/paper_trail/version_queries.ex
This PR removes the `@repo` module attribute from VersionQueries.
I had the problem 
>     ** (UndefinedFunctionError) function Repo.all/1 is undefined (module Repo is not available)
when I used distillery to create a release.
Compared to other libraries, the usage of module attributes seems to be the difference so I tried to replace them and it worked.
I am still pretty new to Elixir and not sure what exactly the problem was, but my guess is that Distillery compiles every file beforehand and according to this: https://elixir-lang.org/getting-started/module-attributes.html#as-constants 
> Every time an attribute is read inside a function, a snapshot of its current value is taken. In other words, the value is read at compilation time and not at runtime.
it looked like the Repo module was …
=> Remove repo module attribute from version_queries

.gitignore, lib/paper_trail.ex, test/paper_trail_test.exs
[Ecto.Repo.delete/2](https://hexdocs.pm/ecto/Ecto.Repo.html#c:delete/2) supports passing a Changeset, but PaperTrail crashes when we try to do that, this PR fixes that.
=> Support delete with changeset

lib/paper_trail.ex, lib/paper_trail/multi.ex
Initial rough draft of a `PaperTrail.Multi` API that wraps `Ecto.Multi` to allow creating multi step transactions using a pipeline.
Inspiration taken from this ticket https://github.com/izelnakri/paper_trail/issues/48.
This PR extracts the logic from the `PaperTrail` module and breaks it down into transaction creation + committing steps in `PaperTrail.Multi`. These functions provide the Multi API and are then reused within `PaperTrail` to implement the non-`Multi` functions.
Since even the non-`Multi` functions require a transaction to apply the paper trail logic, I thought this might be a nice approach.
API wise, it's almost 1-to-1 with `Ecto.Multi`, the only exceptions are:
- no `delete_all`
- no `insert_all`
- no `insert_or_update`
- no `update_all`
- Multi transaction should be …
=> Ecto Multi Support Proposition

mix.exs
Postgres seems to be used only in these environments, so we can reduce its scope to avoid polluting the client applications that use a different database.
Jason also seems to be used only for testing, db driver libraries have their own json configuration.
=> Require postgrex and jason only for dev and test

lib/version.ex, mix.exs, test/test_helper.exs
I am really sorry, the last release will break if the client doesn't have postgrex there because it's listed as one of the applications to be started, my bad :/
I have plugged this into an example with myxql to test it now and realized that it can't handle the origin to be read after writing, so I also made it optional.
=> Make it compatible with mariadb

README.md
Its out of sync with published Hex version.
=> Update installation version in README.md

mix.exs
So that Hex packages earmark_parser, makeup, makeup_elixir, and nimble_parsec aren't pulled in to users of this library.
(The [tests on CI](https://app.circleci.com/pipelines/github/izelnakri/paper_trail/) were already failing and as far as I can tell, this change doesn't make more tests fail.)
=> Require ex_doc dependency only for ":docs".

lib/paper_trail.ex, lib/paper_trail/multi.ex, priv/repo/migrations/20200827222744_add_uniqueness_constraint_to_companies_name.exs, test/paper_trail/bang_functions_simple_mode_test.exs, test/paper_trail/bang_functions_strict_mode_test.exs, test/paper_trail/base_test.exs, test/paper_trail/strict_mode_test.exs
Pass through any ecto options to `insert` and `insert!`. This does not (yet) thread the options through to`update` and `update!`. If it is acceptable as is, we can add the option to updates on a new pull request 😎 
This might address https://github.com/izelnakri/paper_trail/issues/32
=> add support for ecto options in insert and insert! functions

README.md, lib/mix/tasks/papertrail/install.ex, lib/version.ex
Add support for different `timestamp` types for the `Version` schema.
Currently only the default `naive_datetime` can be used. In order to use `utc_datetime` or `utc_datetime_usec` it should be specified as a type option.
This PR adds a configuration field which for this purpose, namely `:paper_trail, :timestamps_type`.
=> Make Version schema's timestamps type configurable

.gitignore, config/test.exs, lib/paper_trail.ex, lib/paper_trail/multi.ex, lib/paper_trail/serializer.ex, lib/version.ex, priv/repo/migrations/20160619190937_add_simple_companies.exs, test/paper_trail/bang_functions_simple_mode_test.exs, test/paper_trail/bang_functions_strict_mode_test.exs, test/paper_trail/base_test.exs, test/paper_trail/strict_mode_test.exs, test/support/simple_models.exs, test/test_helper.exs, test/version/paper_trail_version_test.exs, test/version/version_queries_test.exs
[Ecto.embedded_dump/2](https://hexdocs.pm/ecto/Ecto.html#embedded_dump/2) is now called when serializing changes, which means custom Ecto fields have their [dump/1](https://hexdocs.pm/ecto/Ecto.Type.html#c:dump/1) callback called if their callback [embed_as/1](https://hexdocs.pm/ecto/Ecto.Type.html#c:embed_as/1) return `:dump` (default is `:self`).
These changes were done only in this commit: https://github.com/rschef/paper_trail/commit/1c97a580ccbfb77c4da9da363d99607446aee569
The following functions were being declared in multiple modules, although they had the same implementation. 
Now all modules delegate to the `PaperTrail.Serializer` module:
```elixir
defdelegate make_version_struct(version, model, options), to: Serializer
defdelegate get_sequence_from_model(changeset), to: …
```
=> Dump fields using Ecto when serializing changes

lib/paper_trail.ex, lib/paper_trail/multi.ex, mix.exs, test/paper_trail/bang_functions_simple_mode_test.exs, test/paper_trail/bang_functions_strict_mode_test.exs, test/paper_trail/base_test.exs, test/paper_trail/strict_mode_test.exs, test/support/simple_models.exs, test/test_helper.exs
=> Enable capture_log to make test output readable

config/test.exs, lib/paper_trail.ex, test/paper_trail/bang_functions_simple_mode_test.exs, test/paper_trail/bang_functions_strict_mode_test.exs
=> Refactor Duplicated Code

lib/paper_trail/serializer.ex, priv/repo/migrations/20160619190938_add_simple_people.exs, test/paper_trail/bang_functions_simple_mode_test.exs, test/paper_trail/base_test.exs, test/support/simple_models.exs
Replaces the functionality of embeds in #21, #30 and #60
For associations there's an easy point to hook in in the `Serializer` as well.
=> Support Ecto Embed

lib/paper_trail/version_queries.ex
Giving options to `get_version/2` and `get_versions/2` triggered a dialyzer warning.  The spec only allowed an empty list as options, hence the PR
=> fix: typespecs for get_version(s)/2

lib/paper_trail.ex, lib/version.ex
I use Dialyzer (via [dialyxir](https://hexdocs.pm/dialyxir/readme.html)) for increased static type safety in most projects I work on, and there are a couple Dialyzer warnings bubbling up from `paper_trail` (full output below). Most stem from the `@spec` for `PaperTrail.model_or_error/2`.
The updated spec for `model_or_error/2` indicates that other keys are allowed in the `{:ok, %{model: model}}` case. I changed the default value of `params` in `PaperTrail.Version.changeset/2`, since `:empty` will cause a raise.
Here's the full warning output:
```
lib/paper_trail.ex:47:no_return
Function insert!/1 has no local return.
________________________________________________________________________________
lib/paper_trail.ex:47:no_return
Function insert!/2 has no local return. …
```
=> fix dialyzer warnings

lib/paper_trail/multi.ex
The direct usage of the `PaperTrail.Multi` module is very hard as it does not have support for multiple updates or deletes in a transaction. Adding the capability of defining the keys for the model and versions in the `update` and `delete` functions will add a lot of functionality and allow people to use this module directly. After merging `PaperTrail` would support multiple stage transactions (in the non-strict mode). This would be very useful to me.
=> (chore): add support for using PaperTrail.Multi directly

lib/paper_trail/multi.ex
The model key was hardcoded to `:model` in the strict mode branch of PaperTrail.Multi.insert/3 and was modified to use the `model_key` variable.
=> Use model_key for insert in strict mode and add initial_version_key

lib/paper_trail.ex, lib/paper_trail/multi.ex, test/paper_trail/base_test.exs
=> add insert_or_update/2 and insert_or_update!/2

README.md
Adds a note to the README about JSON limitations supporting some Postgres data types like composite and range types.
=> Add readme note about Postgres type support
